"""gender and city removed

Revision ID: a7b798f58f0a
Revises: baf928dcbb4b
Create Date: 2026-04-15 20:08:47.100427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7b798f58f0a'
down_revision: Union[str, Sequence[str], None] = 'baf928dcbb4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'city')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.VARCHAR(length=10), nullable=True))
    op.add_column('users', sa.Column('city', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
